import type { ExtractedReport } from "./report.types";

/** Empty inputs are intentionally invalid until reviewed; no invented zeroes or sample values. */
export function newManualReport(): ExtractedReport {
  const image = "data:image/png;base64,";
  return {
    sourceFormat: "legacy",
    printClientLogo: "",
    printChartMode: "image",
    printChartImage: "",
    printTitle: "",
    schematic: { approved: false, segments: [], landmarks: [] },
    financialPlannedProgress: null,
    financialDifference: null,
    anticipatedPayment: null,
    constructionDaysWithVos: "Not provided",
    completionDateWithVos: "Not provided",
    contractRows: [],
    contacts: [],
    activityStatusImage: "",
    details: [],
    attachments: [],
    chartSource: "table",
    projectName: "",
    projectNumber: "Not provided",
    projectType: "Not provided",
    slug: "new-project",
    region: "",
    reportMonth: "",
    reportNumber: "Not provided",
    dataAsOf: "",
    contractValue: "",
    currency: "R.O.",
    awardDate: "",
    startDate: "",
    completionDate: "",
    expectedCompletionDate: "Not provided",
    mobilizationDays: NaN,
    constructionDays: NaN,
    elapsedDays: NaN,
    remainingDays: NaN,
    plannedProgress: NaN,
    actualProgress: NaN,
    variance: NaN,
    monthPlannedProgress: null,
    monthActualProgress: null,
    financialProgress: NaN,
    paidAmount: null,
    plannedMachinery: NaN,
    actualMachinery: NaN,
    plannedManpower: NaN,
    actualManpower: NaN,
    brief: "",
    activitiesText: "",
    activities: [],
    schedule: [],
    clientName: "",
    clientDepartment: "",
    contractorName: "Not provided",
    contractorRepresentative: "",
    contractorRole: "",
    contractorPhone: "",
    consultantName: "Not provided",
    consultantRepresentative: "",
    consultantRole: "",
    consultantPhone: "",
    engineerName: "",
    engineerPhone: "",
    footerCode: "Not provided",
    revision: "Not provided",
    scope: [],
    layers: [],
    trades: [],
    rawOcrText: "",
    logoImage: image,
    logoImageSource: "pdf",
    logoImageWidth: 0,
    logoImageHeight: 0,
    layoutImage: image,
    layoutImageSource: "pdf",
    layoutImageWidth: 0,
    layoutImageHeight: 0,
    progressChartImage: image,
    photos: Array.from({ length: 4 }, () => ({
      caption: "",
      sub: "",
      dataUrl: image,
      source: "pdf" as const,
      width: 0,
      height: 0,
    })),
  };
}

export function nextMonthlyReport(previous: ExtractedReport): ExtractedReport {
  const blank = newManualReport();
  return {
    ...previous,
    useRaysutReferenceLayout: false,
    layoutUpdates: [],
    previousMonthReference: {
      reportMonth: previous.reportMonth,
      actualProgress: Number.isFinite(previous.actualProgress) ? previous.actualProgress : null,
      financialProgress: Number.isFinite(previous.financialProgress)
        ? previous.financialProgress
        : null,
      paidAmount: previous.paidAmount,
    },
    printChartImage: "",
    reportMonth: "",
    dataAsOf: "",
    reportNumber: "Not provided",
    rawOcrText: "",
    elapsedDays: NaN,
    remainingDays: NaN,
    plannedProgress: NaN,
    actualProgress: NaN,
    variance: NaN,
    monthPlannedProgress: null,
    monthActualProgress: null,
    financialPlannedProgress: null,
    financialProgress: NaN,
    financialDifference: null,
    paidAmount: null,
    anticipatedPayment: null,
    actualMachinery: NaN,
    actualManpower: NaN,
    photos: blank.photos,
    activityStatusImage: "",
    sourceDocument: undefined,
    details: [],
    attachments: [],
    expectedCompletionDate: "Not provided",
    activities: previous.activities.map((a) => ({ ...a, planned: null, actual: null, diff: null })),
    trades: previous.trades.map((t) => ({ ...t, status: "unknown" })),
    schematic: { ...previous.schematic, approved: false },
  };
}

/** Evidence file for an admin-entered report; binary assets live in the report revision itself. */
export function manualSource(report: ExtractedReport) {
  return JSON.stringify({
    origin: "manual-entry",
    projectName: report.projectName,
    reportMonth: report.reportMonth,
    dataAsOf: report.dataAsOf,
  });
}
